version: "3.9"

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: wQ7Xq2hmZVBmvjzG
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data